version: '3.8'

services:
  app:
    build:
      context: . # this should be the directory with your Dockerfile for the Java Spring app
    ports:
      - "8080:8080" # map app port to local
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/magustadatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: magustadatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

    ports:
      - "5432:5432" # map Postgres port to local (optional)
    volumes:
      - postgres_data:/var/lib/postgresql/data # persistent storage

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: