spring.application.name=Aikelt

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://dpg-csnqu11u0jms738vj680-a:5432/magustadb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.platform=postgresql

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL file initialization
spring.sql.init.mode=never
spring.datasource.initialization-mode=never

# Logging configuration: Reducing verbosity
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.springframework.jdbc.core.JdbcTemplate=ERROR
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=ERROR
logging.level.org.springframework.web.client=ERROR
logging.level.org.springframework.http.client=ERROR
logging.level.org.springframework.jdbc=ERROR
logging.level.org.apache.coyote.http11=ERROR
logging.level.org.apache.coyote.http11.Http11Processor=ERROR

# OpenAI API configuration
openai.model=gpt-4o-mini
openai.api.url=https://api.openai.com/v1/chat/completions
openai.api.key=${OPENAI_API_KEY}

# Server and connection configurations
server.connection-timeout=30s
server.tomcat.max-threads=200
spring.datasource.tomcat.max-wait=60000
spring.datasource.tomcat.connection-timeout=60000

# Tomcat settings and logging optimizations
server.max-http-header-size=65536
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
server.http.version=HTTP/1.1
server.ssl.enabled=false
server.tomcat.uri-encoding=UTF-8
server.tomcat.max-http-header-size=65536
server.error.whitelabel.enabled=false
server.error.path=/error


# Management endpoints configuration
management.endpoints.web.exposure.include=info
#management.endpoint.health.show-details=always

# Disable Tomcat Native library message
server.tomcat.native=false

# Additional Settings (Optional)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

