# Application Name
spring.application.name=Aikelt

# PostgreSQL configuration
# This are production
# spring.datasource.url=jdbc:postgresql://dpg-csnqu11u0jms738vj680-a:5432/magustadb
# spring.datasource.username=${DB_USERNAME}
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.platform=postgresql
# spring.datasource.driver-class-name=org.postgresql.Driver

# This are production
# Hibernate configuration
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.show-sql=false

# SQL file initialization
spring.sql.init.mode=always
spring.datasource.initialization-mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Logging configuration: Reducing verbosity
logging.level.root=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=ERROR
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=ERROR
logging.level.org.springframework.web.client=ERROR
logging.level.org.springframework.http.client=ERROR
logging.level.org.springframework.jdbc=ERROR
logging.level.org.apache.coyote.http11=ERROR
logging.level.org.apache.coyote.http11.Http11Processor=ERROR

# OpenAI API configuration
openai.model=gpt-4o-mini
openai.api.url=https://api.openai.com/v1/chat/completions
#openai.api.key=${OPENAI_API_KEY}
//openai.api.key=



# Server and connection configurations
server.connection-timeout=10s
server.tomcat.max-threads=100
spring.datasource.tomcat.max-wait=30000
spring.datasource.tomcat.connection-timeout=30000

# Tomcat settings and logging optimizations
server.max-http-header-size=65536
server.http.version=HTTP/1.1
server.ssl.enabled=false
server.tomcat.uri-encoding=UTF-8
server.tomcat.max-http-header-size=65536
server.error.whitelabel.enabled=false
server.error.path=/error

# HTTP encoding settings
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# Management endpoints configuration
management.endpoints.web.exposure.include=info
# management.endpoint.health.show-details=always

# Disable Tomcat Native library message
server.tomcat.native=false


#H2 database only dev
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-ui